### ISSUE TITLE
Support fzy (or user defined fuzzy finder)

### ISSUE THREAD

**Issue by HaleTom** [ytet5uy4/fzf-widgets#35]
`fzy` does smarter matching than `fzf`.

Would you consider supporting user selectable finders (eg fzy, fzf, peco, percol, selecta) via a variable?

Ideally, this variable could have a value like:  `fzy:fzf:peco:percol:selecta`.

**Comment by ytet5uy4** [comment]
@HaleTom
Sorry for replying so late. :bow:

Thank you for your proposal!
But I'm not planning to support user selectable finders via a variable, because it's very difficult to try many fuzzy finder and check every feature over the long run.
And I don't use multiple fuzzy finders for different purposes.
I think I should create plugin each fuzzy finder, so I close this issue. :+1:
